version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    ports:
      - 8800:80
    environment:
      - PMA_HOST=metro.proxy.rlwy.net:13374
      - PMA_PORT=13374
      - PMA_USER=root
      - PMA_PASSWORD=AdDbDFCKJrRWmJCbqBpMhQlhvlJvwNNf